services:
  # --- INFRAESTRUTURA ---
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fast_queue_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "wal_level=logical"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d fast_queue_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,OUTSIDE://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9092 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - network.host=0.0.0.0
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 >/dev/null || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 10
      start_period: 40s

  # --- NOSSOS MICROSSERVIÇOS ---
  queue-service:
    build:
      context: .
      dockerfile: ./services/queue-service/Dockerfile
    container_name: queue-service
    ports:
      - "8000:8000"
    env_file:
      - ./services/queue-service/.env
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./services/queue-service/src:/app/src
      - ./libs:/app/libs
      - ./services/queue-service/firebase.json:/app/firebase.json
    environment:
      - FIRESTORE_EMULATOR_HOST=host.docker.internal:8080
      - FIREBASE_AUTH_EMULATOR_HOST=host.docker.internal:9099
      - GCLOUD_PROJECT=fast-queue-493301
      - FIREBASE_ADMIN_SDK_PATH=/app/firebase.json
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  payment-service:
    build:
      context: .
      dockerfile: ./services/payment-service/Dockerfile
    container_name: payment-service
    ports:
      - "8001:8001"
    env_file:
      - ./services/payment-service/.env
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    volumes:
      - ./services/payment-service/src:/app/src
      - ./libs:/app/libs
    command: uvicorn src.main:app --host 0.0.0.0 --port 8001 --reload

  search-service:
    build:
      context: .
      dockerfile: ./services/search-service/Dockerfile
    container_name: search-service
    ports:
      - "8002:8002"
    env_file:
      - ./services/search-service/.env
    restart: on-failure
    depends_on:
      kafka:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./services/search-service/src:/app/src
      - ./libs:/app/libs
    environment:
      - KAFKA_SERVER=kafka:9092
    command: uvicorn src.main:app --host 0.0.0.0 --port 8002 --reload

  api-gateway:
    image: nginx:alpine
    container_name: api-gateway
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      queue-service:
        condition: service_started
      payment-service:
        condition: service_started
      search-service:
        condition: service_started
      frontend:
        condition: service_started

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

  debezium:
    image: debezium/connect:2.5
    container_name: debezium
    depends_on:
      - kafka
      - postgres
    ports:
      - "8083:8083"
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses

volumes:
  postgres_data: