server {
    add_header Cross-Origin-Opener-Policy "unsafe-none";
    
    listen 80;

    # 1. Rotas de API (Sempre coloque as mais específicas primeiro)
    
    location /v1/queues {
        proxy_pass http://queue-service:8000;
        proxy_set_header Host $host;
    }

    location /v1/payments {
        proxy_pass http://payment-service:8001;
        proxy_set_header Host $host;
    }

    # ATENÇÃO: Verifique se o prefixo aqui é exatamente /v1/search
    location /v1/search {
        proxy_pass http://search-service:8002;
        proxy_set_header Host $host;
    }

    # 2. Rota do Frontend (Catch-all)
    # Esta deve ser a ÚLTIMA regra do arquivo
    location / {
        proxy_pass http://frontend:5173;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }
    
}